[package]
name = "rushls"
version = "0.1.0"
edition = "2024"

[dependencies]
arc-swap = "1"
derive_more = { version = "2", features = ["debug", "display"] }
bytes = "1.12.1"
ffmpeg-sys-next = { version = "8.1.0", default-features = false, features = ["avformat"] }
nz = "0.4"
parking_lot = "0.12"
scuffle-rtmp = "0.2.3"
subtle = "2"
thiserror = "2"
time = { version = "0.3", features = ["formatting"] }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
urlencoding = "2"
axum = { version = "0.8.9", default-features = false, features = ["http1", "http2", "original-uri", "query", "tokio"] }
http-body-util = "0.1.4"
http-body = "1.1.0"

[dev-dependencies]
base64 = "0.22"
tokio = { version = "1", features = ["test-util"] }
