//! Packaged rendition and presentation fixtures.
//!
//! The defaults describe a pass-through CMAF publication of the fixtures in
//! [`media::fixtures`](crate::media::fixtures): one output per input track,
//! six-second segments cut into one-second chunks. Tests that care about
//! reconnect matching override the [`RenditionKey`]; tests that care about
//! packaging mode override the chunk target; nothing else has to be spelled.

use std::{num::NonZero, sync::Arc, time::SystemTime};

use parking_lot::Mutex;

use crate::{
    domain::{
        DiscoveredTrack, FrameRate, MediaKind, SessionId, TickDuration, Timebase, TrackId,
        fixtures as domain, rfc6381,
    },
    media::PresentationPlan,
    observe::{EventObserver, EventSink, Events, SessionEvent},
};

use super::{
    MediaSegmentFormat, PackagedPresentation, PackagedRendition, PackagingRenditionId,
    RenditionConfig, RenditionKey, RenditionMedia,
};

/// Collects the session events a muxer emits, for tests that assert on them.
#[derive(Default)]
pub struct RecordedEvents(Mutex<Vec<SessionEvent>>);

impl RecordedEvents {
    /// A sink and the recorder reading everything sent to it.
    pub fn sink() -> (EventSink, Arc<Self>) {
        let recorder = Arc::new(Self::default());
        let events = Events::new(Arc::clone(&recorder) as Arc<dyn EventObserver>);
        (events.scoped(SessionId(nz::u64!(1))), recorder)
    }

    pub fn events(&self) -> Vec<SessionEvent> {
        self.0.lock().clone()
    }
}

impl EventObserver for RecordedEvents {
    fn observe(&self, _session: SessionId, event: SessionEvent) {
        self.0.lock().push(event);
    }
}

/// An event sink for tests with nothing to assert about what was emitted.
pub fn discarded_events() -> EventSink {
    Events::default().scoped(SessionId(nz::u64!(1)))
}

/// Minimal AVC configuration and access units generated by FFmpeg/libx264 for
/// a 16×16, two-frames-per-second stream. Keeping encoded bytes here lets CMAF
/// integration tests package without depending on an encoder or command-line
/// binary at test time.
pub const H264_EXTRADATA: &[u8] = &[
    0x01, 0x64, 0x00, 0x0a, 0xff, 0xe1, 0x00, 0x17, 0x67, 0x64, 0x00, 0x0a, 0xac, 0xb2, 0x3d, 0x80,
    0x88, 0x00, 0x00, 0x03, 0x00, 0x08, 0x00, 0x00, 0x03, 0x00, 0x20, 0x78, 0x91, 0x32, 0x40, 0x01,
    0x00, 0x06, 0x68, 0xeb, 0xc3, 0xcb, 0x22, 0xc0, 0xfd, 0xf8, 0xf8, 0x00,
];

pub const H264_IDR: &[u8] = &[
    0x00, 0x00, 0x00, 0x0e, 0x65, 0x88, 0x84, 0x05, 0x3f, 0xfe, 0xf7, 0xc7, 0x4f, 0xc0, 0xa6, 0xea,
    0xdc, 0x27,
];

pub const H264_P: &[u8] = &[
    0x00, 0x00, 0x00, 0x08, 0x41, 0x9a, 0x3b, 0x10, 0x53, 0xff, 0xfe, 0xf0,
];

/// AudioSpecificConfig for the 48 kHz mono AAC-LC fixture below.
pub const AAC_EXTRADATA: &[u8] = &[0x11, 0x88, 0x56, 0xe5, 0x00];

/// One valid AAC access unit from the checked-in Matroska priming fixture.
///
/// Keeping the real encoded frame in the shared mux fixtures allows output to
/// be demuxed and inspected without an encoder or FFmpeg CLI at test runtime.
pub const AAC_FRAME: &[u8] = &[
    0xde, 0x02, 0x00, 0x4c, 0x61, 0x76, 0x63, 0x36, 0x32, 0x2e, 0x32, 0x38, 0x2e, 0x31, 0x30, 0x32,
    0x00, 0x02, 0x50, 0x6d, 0x5c, 0xe9, 0x9a, 0x24, 0x1e, 0xa5, 0xdf, 0x5c, 0x77, 0xaa, 0xe7, 0x2b,
    0xd7, 0xef, 0xad, 0x2e, 0xb8, 0x95, 0x24, 0xe6, 0x6b, 0x9f, 0x3c, 0xc8, 0xf4, 0x9c, 0xf9, 0xef,
    0x42, 0x08, 0x2d, 0xab, 0x65, 0xa9, 0xa6, 0xda, 0xb6, 0x7d, 0x7b, 0xea, 0x36, 0xd5, 0xb3, 0xd9,
    0x5d, 0xab, 0xd9, 0x5d, 0xab, 0x6d, 0x66, 0x1b, 0x6b, 0x30, 0xe9, 0x2f, 0x39, 0xd1, 0x44, 0x08,
    0x4d, 0x53, 0x0e, 0xbb, 0x43, 0xf6, 0xae, 0xf1, 0xd9, 0xdf, 0x33, 0xde, 0x5c, 0xd3, 0xb3, 0xbe,
    0x67, 0xbc, 0xb9, 0xa7, 0x8b, 0xb6, 0x6e, 0x8e, 0xcd, 0x38, 0xb6, 0xcd, 0xd9, 0xda, 0x37, 0x35,
    0x61, 0x34, 0xd5, 0x33, 0x4d, 0x73, 0x6e, 0xce, 0xd9, 0xbb, 0x3b, 0x34, 0xe6, 0xad, 0x9b, 0xad,
    0xb3, 0x4e, 0x6a, 0xcd, 0x39, 0xab, 0x6d, 0xca, 0xb2, 0x9c, 0x76, 0x37, 0x1d, 0x94, 0xe3, 0xb1,
    0xb8, 0xec, 0x6e, 0x3b, 0x1b, 0x8e, 0xc6, 0xe3, 0xb1, 0xb8, 0xec, 0x6e, 0x3b, 0x1b, 0x8e, 0xc6,
    0xe3, 0xb1, 0xb8, 0xec, 0x6d, 0x89, 0x4a, 0xa5, 0x2a, 0x94, 0xaa, 0x52, 0xa9, 0x4a, 0xa5, 0x2a,
    0x94, 0xaa, 0x52, 0xa9, 0x4a, 0xa5, 0x2a, 0x9f, 0x5f, 0x9f, 0x5f, 0x9f, 0x5f, 0x9f, 0x5f, 0x9f,
    0x5f, 0x9f, 0x55, 0x12, 0x51, 0x25, 0x12, 0x51, 0x25, 0x12, 0x51, 0x25, 0x3e, 0xbf, 0x3e, 0xbf,
    0x3e, 0xbf, 0x3e, 0xbf, 0x3e, 0xbf, 0x3e, 0xbf, 0x3e, 0xaa, 0x24, 0xa2, 0x4a, 0x24, 0xa2, 0x4a,
    0x24, 0xa2, 0x4a, 0x24, 0xa2, 0x4a, 0x24, 0xa2, 0x4a, 0x24, 0xa2, 0x4a, 0x24, 0xa2, 0x4a, 0x24,
    0xa2, 0x4a, 0x24, 0xa2, 0x4a, 0x24, 0xa2, 0x4a, 0x24, 0xa2, 0x4a, 0x70, 0x54, 0xb2, 0xcb, 0x2c,
    0xb2, 0xcb, 0x2f, 0xf9, 0x7f, 0xcb, 0xfe, 0x5f, 0xf2, 0xff, 0x97, 0xfc, 0xbf, 0xe5, 0xff, 0x2c,
    0xb2, 0xcb, 0x2c, 0xb2, 0xcb, 0x2f,
];

/// Samples in one AAC-LC access unit — the audio cadence quantum.
pub const AAC_FRAME_SAMPLES: u64 = 1_024;

/// Segment and chunk targets in the rendition's own timebase.
///
/// `chunk_target` of `None` selects segment-only packaging, which the store
/// treats as a different contract rather than a tuning knob.
pub fn config(
    timebase: Timebase,
    segment_target: TickDuration,
    chunk_target: Option<TickDuration>,
) -> RenditionConfig {
    config_with_maximum(timebase, segment_target, segment_target, chunk_target)
}

/// A config whose segments may run past their target, as an extending
/// boundary policy allows.
pub fn config_with_maximum(
    timebase: Timebase,
    segment_target: TickDuration,
    maximum_segment_duration: TickDuration,
    chunk_target: Option<TickDuration>,
) -> RenditionConfig {
    RenditionConfig {
        timebase,
        segment_target: NonZero::new(segment_target).expect("a segment target is nonzero"),
        maximum_segment_duration: NonZero::new(maximum_segment_duration)
            .expect("a maximum segment duration is nonzero"),
        chunk_target: chunk_target
            .map(|target| NonZero::new(target).expect("a chunk target is nonzero")),
        segment_format: MediaSegmentFormat::Cmaf,
    }
}

/// The advertised output shape for a test rendition of each kind.
pub fn media(kind: MediaKind) -> RenditionMedia {
    match kind {
        MediaKind::Audio => RenditionMedia::Audio {
            sample_rate: nz::u32!(48_000),
            channels: nz::u16!(2),
        },
        MediaKind::Subtitle => RenditionMedia::Subtitle,
        MediaKind::Video => RenditionMedia::Video {
            width: nz::u32!(1920),
            height: nz::u32!(1080),
            frame_rate: Some(FrameRate::new(nz::u32!(30), nz::u32!(1))),
            video_range: None,
        },
    }
}

/// The RFC 6381 string for a fixture track of `kind` carrying no extradata.
///
/// Derived rather than hardcoded so a change to
/// [`domain::fixtures::codec`](crate::domain::fixtures::codec) cannot leave the
/// declared codec and the advertised string disagreeing.
pub fn codecs(kind: MediaKind) -> Arc<str> {
    rfc6381(domain::codec(kind), None).expect("fixture codecs are representable")
}

/// Builds one packaged rendition, overriding only what a test cares about.
#[derive(Clone, Debug)]
pub struct RenditionBuilder(PackagedRendition);

impl RenditionBuilder {
    /// A 90 kHz output of `kind` with six-second segments and one-second chunks.
    pub fn new(packaging_rendition_id: u32, kind: MediaKind) -> Self {
        Self(PackagedRendition {
            packaging_rendition_id: PackagingRenditionId(packaging_rendition_id),
            key: RenditionKey::new(format!("{kind:?}/{packaging_rendition_id}")),
            source_tracks: Arc::from([TrackId(0)]),
            config: config(Timebase::hz90k(), 6 * 90_000, Some(90_000)),
            media: media(kind),
            codecs: codecs(kind),
            name: Arc::from(format!("{kind:?} {packaging_rendition_id}")),
            language: None,
            is_default: false,
            declared_bandwidth: None,
        })
    }

    /// A pass-through output of one discovered track.
    ///
    /// This is what a real pass-through muxer does, spelled once: take the
    /// track's timebase, name it as the source, and derive the RFC 6381 string
    /// from the codec *and its configuration bytes* rather than from a guess
    /// keyed on media kind. A test that gives its track real extradata gets the
    /// refined `avc1.640028` form out of this without doing anything else.
    pub fn for_track(packaging_rendition_id: u32, track: &DiscoveredTrack) -> Self {
        let mut builder = Self::new(packaging_rendition_id, track.kind())
            .key(&RenditionKey::for_source(track).0)
            .source_tracks(&[track.id.0]);
        builder.0.config.timebase = track.timebase;
        builder.0.language = track.language.as_deref().map(Arc::from);
        if let Some(codecs) = track.rfc6381_codec() {
            builder.0.codecs = codecs;
        }
        builder
    }

    #[must_use]
    pub fn key(mut self, key: &str) -> Self {
        self.0.key = RenditionKey::new(key);
        self
    }

    #[must_use]
    pub fn source_tracks(mut self, tracks: &[u32]) -> Self {
        self.0.source_tracks = tracks.iter().copied().map(TrackId).collect();
        self
    }

    #[must_use]
    pub fn config(mut self, config: RenditionConfig) -> Self {
        self.0.config = config;
        self
    }

    /// Switches between chunked and segment-only packaging, keeping the
    /// rendition's timebase and segment target.
    #[must_use]
    pub fn chunked(mut self, chunked: bool) -> Self {
        let chunk_target = self.0.config.chunk_target.or(NonZero::new(90_000));
        self.0.config.chunk_target = chunked.then_some(chunk_target).flatten();
        self
    }

    #[must_use]
    pub fn is_default(mut self, is_default: bool) -> Self {
        self.0.is_default = is_default;
        self
    }

    pub fn build(self) -> PackagedRendition {
        self.0
    }
}

/// The default pass-through topology over `renditions`, anchored at the epoch.
pub fn presentation(
    input: &PresentationPlan,
    renditions: Vec<PackagedRendition>,
) -> PackagedPresentation {
    presentation_at(SystemTime::UNIX_EPOCH, input, renditions)
}

/// As [`presentation`], with an explicit wall-clock origin.
///
/// Separate publications need distinct anchors for the store's PDT bookkeeping
/// to be observable, so that case gets its own entry point rather than an
/// `Option` every other caller has to pass.
pub fn presentation_at(
    time_anchor: SystemTime,
    input: &PresentationPlan,
    renditions: Vec<PackagedRendition>,
) -> PackagedPresentation {
    PackagedPresentation::with_default_topology(time_anchor, input, renditions)
        .expect("test packaged presentation is valid")
}

/// Read edit-list entries from a generated initialization for timing assertions.
pub fn edit_list(payload: &crate::domain::Payload) -> Vec<(u64, i64)> {
    let bytes = payload.as_bytes();
    let Some(type_offset) = bytes.windows(4).position(|window| window == b"elst") else {
        return Vec::new();
    };
    let box_start = type_offset
        .checked_sub(4)
        .expect("box type follows its size");
    let box_size = u32::from_be_bytes(
        bytes[box_start..type_offset]
            .try_into()
            .expect("box size is four bytes"),
    ) as usize;
    let box_end = box_start + box_size;
    assert!(box_size >= 16 && box_end <= bytes.len());
    let body = &bytes[type_offset + 4..box_end];
    let version = body[0];
    let entries = u32::from_be_bytes(body[4..8].try_into().expect("entry count is four bytes"));
    let mut cursor = 8;
    (0..entries)
        .map(|_| match version {
            0 => {
                let duration = u64::from(u32::from_be_bytes(
                    body[cursor..cursor + 4]
                        .try_into()
                        .expect("duration is four bytes"),
                ));
                let media_time = i64::from(i32::from_be_bytes(
                    body[cursor + 4..cursor + 8]
                        .try_into()
                        .expect("media time is four bytes"),
                ));
                cursor += 12;
                (duration, media_time)
            }
            1 => {
                let duration = u64::from_be_bytes(
                    body[cursor..cursor + 8]
                        .try_into()
                        .expect("duration is eight bytes"),
                );
                let media_time = i64::from_be_bytes(
                    body[cursor + 8..cursor + 16]
                        .try_into()
                        .expect("media time is eight bytes"),
                );
                cursor += 20;
                (duration, media_time)
            }
            _ => panic!("unsupported edit-list version"),
        })
        .collect()
}
